# Generated by Django 4.1.4 on 2023-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penner', '0002_alter_expense_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-purchased']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='location',
            field=models.CharField(choices=[('TH', 'Thrift'), ('ES', 'Estate'), ('YS', 'Yard Sale'), ('GW', 'GW Online'), ('MP', 'Marketplace'), ('PR', 'Private Sale'), ('OT', 'Other')], default='Thrift', max_length=2, verbose_name='Location Type'),
        ),
    ]
