# Generated by Django 4.1.4 on 2022-12-18 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penner', '0002_alter_expense_buyer_alter_expense_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='location',
            field=models.CharField(choices=[('TH', 'Thrift'), ('ES', 'Estate'), ('YS', 'Yard Sale'), ('GW', 'GW Online'), ('MP', 'Marketplace'), ('PR', 'Private Sale'), ('OT', 'Other')], default='Thrift', max_length=2),
        ),
        migrations.AlterField(
            model_name='expense',
            name='purchased',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
