# Generated by Django 4.1.4 on 2023-02-09 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penner', '0003_alter_expense_location_alter_expense_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='buyer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='penner_expense', to=settings.AUTH_USER_MODEL),
        ),
    ]
